### ISSUE TITLE
Publish to bioconda

### ISSUE THREAD

**Issue by J-Wall** [kdm9/axe#14]
Hey Kevin,

Just stumbled across this, and it's exactly what I was looking for, and works great!

Would you consider putting it on bioconda if only to make my life slightly easier when deploying it in our pipeline? If it's a hassle, I could give it a go.

Cheers,
Jesse

**Comment by J-Wall** [comment]
I just saw that this was attempted a couple of years ago... bioconda/bioconda-recipes#15463

Would be nice to get it working!

**Comment by kdm9** [comment]
@J-Wall sorry for the extreme delay, but I got this working last night and now have a conda package in the kdm801 channel: https://anaconda.org/kdm801/axe-demultiplexer

I'll do what I can to get it into bioconda, but there are a few larger issues there (like splitting vendored code) which means that might not be very quick. To be clear: `mamba install -c kdm801 axe-demultiplexer` should get you this new pkg.

Best, and sorry again for the long silence,
K
